!SESSION 2021-06-12 21:04:28.306 -----------------------------------------------
eclipse.buildId=4.8.0.I20180611-0500
java.version=1.8.0_172
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=ja_JP
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

This is a continuation of log file C:\pleiades\workspace\atcoder\.metadata\.bak_0.log
Created Time: 2021-06-12 21:06:38.943

!ENTRY org.eclipse.launchbar.core 2 0 2021-06-12 21:06:38.943
!MESSAGE Enablement expression is missing for config provider for org.eclipse.cdt.arduino.core.descriptorType

!ENTRY org.eclipse.launchbar.core 2 0 2021-06-12 21:06:38.947
!MESSAGE Enablement expression is missing for descriptor type org.eclipse.cdt.debug.core.coreBuildDescriptorType

!ENTRY org.eclipse.launchbar.core 2 0 2021-06-12 21:06:38.949
!MESSAGE Enablement expression is missing for config provider for org.eclipse.cdt.debug.core.coreBuildDescriptorType

!ENTRY org.eclipse.launchbar.core 2 0 2021-06-12 21:06:38.949
!MESSAGE Enablement expression is missing for config provider for org.eclipse.cdt.debug.core.coreBuildDescriptorType

!ENTRY org.eclipse.launchbar.core 2 0 2021-06-12 21:06:38.952
!MESSAGE Enablement expression is missing for config provider for org.eclipse.cdt.debug.core.coreBuildDescriptorType

!ENTRY org.eclipse.launchbar.core 2 0 2021-06-12 21:06:38.953
!MESSAGE Enablement expression is missing for config provider for org.eclipse.cdt.debug.core.coreBuildDescriptorType

!ENTRY org.python.pydev.shared_core 1 1 2021-06-12 21:06:39.136
!MESSAGE 存在しないファイルを追跡できません: C:\Users\tohoseal\Anaconda3\envs\python_test_project\DLLs
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Users\tohoseal\Anaconda3\envs\python_test_project\DLLs
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:54)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:459)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:440)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:66)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:88)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:156)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)

!ENTRY org.python.pydev.shared_core 1 1 2021-06-12 21:06:39.148
!MESSAGE 存在しないファイルを追跡できません: C:\Users\tohoseal\Anaconda3\envs\python_test_project\lib
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Users\tohoseal\Anaconda3\envs\python_test_project\lib
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:54)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:459)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:440)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:66)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:88)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:156)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)

!ENTRY org.python.pydev.shared_core 1 1 2021-06-12 21:06:39.148
!MESSAGE 存在しないファイルを追跡できません: C:\Users\tohoseal\Anaconda3\envs\python_test_project
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Users\tohoseal\Anaconda3\envs\python_test_project
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:54)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:459)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:440)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:66)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:88)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:156)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)

!ENTRY org.python.pydev.shared_core 1 1 2021-06-12 21:06:39.150
!MESSAGE 存在しないファイルを追跡できません: C:\Users\tohoseal\Anaconda3\envs\python_test_project\lib\site-packages
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Users\tohoseal\Anaconda3\envs\python_test_project\lib\site-packages
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:54)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:459)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:440)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:66)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:88)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:156)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)

!ENTRY org.eclipse.epp.logging.aeri.ide 2 17 2021-06-12 21:06:44.127
!MESSAGE Server ‘org.eclipse.epp.logging.aeri.ide.server’ failed with exception: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $. ; バージョン: 2.0.7.v20170906-1327
!STACK 0
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
	at com.google.gson.Gson.fromJson(Gson.java:888)
	at com.google.gson.Gson.fromJson(Gson.java:853)
	at com.google.gson.Gson.fromJson(Gson.java:802)
	at org.eclipse.epp.internal.logging.aeri.ide.server.json.Json.deserialize(Json.java:91)
	at org.eclipse.epp.internal.logging.aeri.ide.server.mars.IO.refreshConfiguration(IO.java:66)
	at org.eclipse.epp.internal.logging.aeri.ide.server.mars.ServerConnection.startUp(ServerConnection.java:124)
	at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:62)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213)
	... 9 more

!ENTRY org.eclipse.cdt.core 1 0 2021-06-12 21:06:54.594
!MESSAGE Indexed '2021-06-12-A' (1 sources, 0 headers) in 0.059 sec: 3 declarations; 0 references; 10 unresolved inclusions; 0 syntax errors; 1 unresolved names (25%)

!ENTRY org.eclipse.linuxtools.docker.core 1 0 2021-06-12 21:06:55.652
!MESSAGE Failed to open connection '' on https://192.168.99.100:2376

!ENTRY org.eclipse.linuxtools.docker.core 1 0 2021-06-12 21:06:55.653
!MESSAGE Failed to open connection '' on https://192.168.99.100:2376

!ENTRY org.eclipse.cdt.core 1 0 2021-06-12 21:07:03.127
!MESSAGE Indexed '2021-06-12-B' (1 sources, 0 headers) in 0.028 sec: 3 declarations; 0 references; 10 unresolved inclusions; 0 syntax errors; 1 unresolved names (25%)

!ENTRY org.python.pydev.shared_core 4 4 2021-06-12 21:07:10.563
!MESSAGE java.io.IOException: Cannot run program "C:\Users\tohoseal\Anaconda3\envs\python_test_project\python.exe": CreateProcess error=2, 指定されたファイルが見つかりません。
!STACK 0
java.lang.RuntimeException: java.io.IOException: Cannot run program "C:\Users\tohoseal\Anaconda3\envs\python_test_project\python.exe": CreateProcess error=2, 指定されたファイルが見つかりません。
	at org.python.pydev.ast.runners.SimpleRunner.run(SimpleRunner.java:314)
	at org.python.pydev.ast.runners.SimpleRunner.run(SimpleRunner.java:280)
	at org.python.pydev.ast.runners.SimpleRunner.runAndGetOutput(SimpleRunner.java:331)
	at org.python.pydev.ast.runners.SimplePythonRunner.runAndGetOutputWithInterpreter(SimplePythonRunner.java:91)
	at org.python.pydev.ast.interpreter_managers.PythonInterpreterManager.doCreateInterpreterInfo(PythonInterpreterManager.java:67)
	at org.python.pydev.ast.interpreter_managers.PythonInterpreterManager.internalCreateInterpreterInfo(PythonInterpreterManager.java:43)
	at org.python.pydev.ast.interpreter_managers.AbstractInterpreterManager.createInterpreterInfo(AbstractInterpreterManager.java:324)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManager$CreateInterpreterInfoCallback.createInterpreterInfo(SyncSystemModulesManager.java:172)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManager.updateStructures(SyncSystemModulesManager.java:278)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler$SynchJob.run(SyncSystemModulesManagerScheduler.java:234)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
Caused by: java.io.IOException: Cannot run program "C:\Users\tohoseal\Anaconda3\envs\python_test_project\python.exe": CreateProcess error=2, 指定されたファイルが見つかりません。
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at org.python.pydev.shared_core.process.ProcessUtils.createProcess(ProcessUtils.java:105)
	at org.python.pydev.ast.runners.SimpleRunner.createProcess(SimpleRunner.java:51)
	at org.python.pydev.ast.runners.SimpleRunner.run(SimpleRunner.java:312)
	... 10 more
Caused by: java.io.IOException: CreateProcess error=2, 指定されたファイルが見つかりません。
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 14 more

!ENTRY org.python.pydev.shared_core 1 1 2021-06-12 21:07:12.866
!MESSAGE 情報: Rebuilding internal caches: C:\pleiades\workspace\atcoder\.metadata\.plugins\com.python.pydev.analysis\python_v1_7dn7h9re6mxzzbcahnwwew1sr\python.pydevsysteminfo
!STACK 0
java.lang.RuntimeException: Unable to read: C:\pleiades\workspace\atcoder\.metadata\.plugins\com.python.pydev.analysis\python_v1_7dn7h9re6mxzzbcahnwwew1sr\python.pydevsysteminfo
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalDependencyInfo.load(AbstractAdditionalDependencyInfo.java:416)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.getAdditionalSystemInfo(AdditionalSystemInterpreterInfo.java:168)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.getAdditionalSystemInfo(AdditionalSystemInterpreterInfo.java:139)
	at com.python.pydev.analysis.system_info_builder.InterpreterInfoBuilder.syncInfoToPythonPath(InterpreterInfoBuilder.java:78)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManager.synchronizeManagerToNameToInfoPythonpath(SyncSystemModulesManager.java:392)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler$SynchJob.run(SyncSystemModulesManagerScheduler.java:257)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
Caused by: java.lang.NumberFormatException: Error getting positive int from: class LIEF::ref_iterator<class std::vector<class LIEF::ELF::Relocation 
	at org.python.pydev.shared_core.string.StringUtils.parsePositiveInt(StringUtils.java:389)
	at com.python.pydev.analysis.additionalinfo.TreeIO.loadTreeFrom(TreeIO.java:247)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalDependencyInfo.loadContentsFromFile(AbstractAdditionalDependencyInfo.java:463)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalDependencyInfo.load(AbstractAdditionalDependencyInfo.java:414)
	... 6 more

!ENTRY org.python.pydev.shared_core 4 4 2021-06-12 21:11:13.616
!MESSAGE ERROR reading shell. Message sent: @@IMPORTS:astropy.convolution._convolve
END@@

ProcessInfo:

 - Executed: C:\Anaconda3\python.exe -u C:\pleiades\eclipse\dropins\PyDev\eclipse\plugins\org.python.pydev.core_6.4.1.201806231219\pysrc\pycompletionserver.py 49953

 - Environment:
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\seal0\AppData\Roaming
CHOCOLATEYINSTALL=C:\ProgramData\chocolatey
CHOCOLATEYLASTPATHUPDATE=132365470270588836
COMMONPROGRAMFILES(X86)=C:\Program Files (x86)\Common Files
COMMONPROGRAMFILES=C:\Program Files\Common Files
COMMONPROGRAMW6432=C:\Program Files\Common Files
COMPOSE_CONVERT_WINDOWS_PATHS=true
COMPUTERNAME=DESKTOP-KB712J3
COMSPEC=C:\WINDOWS\system32\cmd.exe
CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2
CUDA_PATH_V10_2=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2
CUDNN_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2
DRIVERDATA=C:\Windows\System32\Drivers\DriverData
FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
FPS_BROWSER_USER_PROFILE_STRING=Default
GNUPLOT_LIB=C:\Program Files\gnuplot\demo;C:\Program Files\gnuplot\demo\games;C:\Program Files\gnuplot\share
GNUTERM=wxt
GTK_BASEPATH=C:\Program Files (x86)\GtkSharp\2.12\
HOMEDRIVE=C:
HOMEPATH=\Users\seal0
LOCALAPPDATA=C:\Users\seal0\AppData\Local
LOGONSERVER=\\DESKTOP-KB712J3
NUMBER_OF_PROCESSORS=12
NVCUDASAMPLES10_2_ROOT=C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.2
NVCUDASAMPLES_ROOT=C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.2
NVTOOLSEXT_PATH=C:\Program Files\NVIDIA Corporation\NvToolsExt\
ONEDRIVE=C:\Users\seal0\OneDrive
ONEDRIVECONSUMER=C:\Users\seal0\OneDrive
OS=Windows_NT
PATH=C:/pleiades/eclipse/jre/bin/../jre/bin/server;C:/pleiades/eclipse/jre/bin/../jre/bin;C:/pleiades/eclipse/jre/bin/../jre/lib/amd64;C:\Python38\Scripts\;C:\Python38\;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\libnvvp;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\gnuplot\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\MAMP\bin\php\php7.2.10;C:\pleiades\xampp\php;C:\ProgramData\ComposerSetup\bin;C:\Anaconda3;C:\Anaconda3\Scripts;C:\Anaconda3\Library\bin;C:\Anaconda3\Lib\site-packages;C:\Program Files\NVIDIA Corporation\Nsight Compute 2019.5.0\;C:\Program Files\CMake\bin;C:\pleiades\eclipse\mingw\bin;C:\pleiades\eclipse\msys\bin;C:\pleiades\eclipse\cygwin\bin;C:\Program Files\PuTTY\;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Users\seal0\Downloads\ffmpeg-n4.4-19-g8d172d9409-win64-gpl-4.4\bin;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin;C:\Users\seal0\AppData\Local\Microsoft\WindowsApps;C:\Users\seal0\AppData\Roaming\Composer\vendor\bin;C:\Users\seal0\AppData\Roaming\npm;C:\Program Files\JetBrains\PyCharm 2020.3.1\bin;;;C:\pleiades\eclipse;
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=9e0a
PROGRAMDATA=C:\ProgramData
PROGRAMFILES(X86)=C:\Program Files (x86)
PROGRAMFILES=C:\Program Files
PROGRAMW6432=C:\Program Files
PROMPT=$P$G
PSMODULEPATH=C:\Program Files (x86)\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\PowerShell
PUBLIC=C:\Users\Public
PYCHARM=C:\Program Files\JetBrains\PyCharm 2020.3.1\bin;
PYTHONPATH=C:\pleiades\eclipse\dropins\PyDev\eclipse\plugins\org.python.pydev.core_6.4.1.201806231219\pysrc\pydev_sitecustomize;C:\Anaconda3\DLLs;C:\Anaconda3\lib;C:\Anaconda3;C:\Anaconda3\lib\site-packages;C:\Anaconda3\lib\site-packages\win32;C:\Anaconda3\lib\site-packages\win32\lib;C:\Anaconda3\lib\site-packages\Pythonwin;C:\Anaconda3\Library\bin
SESSIONNAME=Console
SYSTEMDRIVE=C:
SYSTEMROOT=C:\WINDOWS
TEMP=C:\Users\seal0\AppData\Local\Temp
TMP=C:\Users\seal0\AppData\Local\Temp
USERDOMAIN=DESKTOP-KB712J3
USERDOMAIN_ROAMINGPROFILE=DESKTOP-KB712J3
USERNAME=seal0
USERPROFILE=C:\Users\seal0
WINDIR=C:\WINDOWS

 - Working Dir:
C:\pleiades\eclipse\dropins\PyDev\eclipse\plugins\org.python.pydev.core_6.4.1.201806231219\pysrc

 - OS:
Windows 10

 - Std output:


 - Err output:

!STACK 0
java.io.IOException: 既存の接続はリモート ホストに強制的に切断されました。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at sun.nio.ch.SocketAdaptor$SocketInputStream.read(SocketAdaptor.java:206)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
	at java.io.InputStream.read(InputStream.java:101)
	at org.python.pydev.ast.codecompletion.shell.AbstractShell.read(AbstractShell.java:455)
	at org.python.pydev.ast.codecompletion.shell.AbstractShell.read(AbstractShell.java:507)
	at org.python.pydev.ast.codecompletion.shell.AbstractShell.writeAndGetResults(AbstractShell.java:693)
	at org.python.pydev.ast.codecompletion.shell.AbstractShell.getImportCompletions(AbstractShell.java:757)
	at org.python.pydev.ast.codecompletion.revisited.modules.CompiledModule.createTokensFromServer(CompiledModule.java:376)
	at org.python.pydev.ast.codecompletion.revisited.modules.CompiledModule.<init>(CompiledModule.java:179)
	at org.python.pydev.ast.codecompletion.revisited.SystemModulesManager.getBuiltinModule(SystemModulesManager.java:322)
	at org.python.pydev.ast.codecompletion.revisited.SystemModulesManager.getModule(SystemModulesManager.java:374)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalDependencyInfo.updateKeysIfNeededAndSave(AbstractAdditionalDependencyInfo.java:259)
	at com.python.pydev.analysis.system_info_builder.InterpreterInfoBuilder.syncInfoToPythonPath(InterpreterInfoBuilder.java:160)
	at com.python.pydev.analysis.system_info_builder.InterpreterInfoBuilder.syncInfoToPythonPath(InterpreterInfoBuilder.java:86)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManager.synchronizeManagerToNameToInfoPythonpath(SyncSystemModulesManager.java:392)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler$SynchJob.run(SyncSystemModulesManagerScheduler.java:257)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)

!ENTRY org.eclipse.jface 2 0 2021-06-12 21:11:38.964
!MESSAGE キーバインドの競合が発生しました。 通常のアクセラレーター操作を妨げる可能性があります。
!SUBENTRY 1 org.eclipse.jface 2 0 2021-06-12 21:11:38.964
!MESSAGE ALT+CTRL+C の競合が発生しました:
Binding(ALT+CTRL+C,
	ParameterizedCommand(Command(AnyEdit.capitalize.command,先頭文字のみ大文字,
		,
		Category(AnyEdit.category,AnyEdit ツール,AnyEdit ツール・キー・バインド,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@45a935e5,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.textEditorScope,,,system)
Binding(ALT+CTRL+C,
	ParameterizedCommand(Command(org.eclipse.linuxtools.changelog.core.actions.KeyActionCommand,ChangeLog エントリーの挿入,
		Insert a ChangeLog entry,
		Category(org.eclipse.linuxtools.changelog,Changelog,Changelog key bindings,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@186c80e,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.textEditorScope,,,system)
Binding(ALT+CTRL+C,
	ParameterizedCommand(Command(org.eclipse.team.svn.ui.command.CommitCommand,コミット...,
		,
		Category(org.eclipse.team.svn.ui.command.category,SVN,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@4ca1874,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)

!ENTRY org.eclipse.equinox.p2.core 4 0 2021-06-12 21:32:14.140
!MESSAGE プロビジョニング例外
!STACK 1
org.eclipse.equinox.p2.core.ProvisionException: http://dl.bintray.com/nodeclipse/nodeclipse/1.0.2f/ のリポジトリーが見つかりません。
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.fail(AbstractRepositoryManager.java:395)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:692)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:107)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:102)
	at org.eclipse.equinox.internal.p2.metadata.repository.CompositeMetadataRepository.addChild(CompositeMetadataRepository.java:165)
	at org.eclipse.equinox.internal.p2.metadata.repository.CompositeMetadataRepository.<init>(CompositeMetadataRepository.java:107)
	at org.eclipse.equinox.internal.p2.metadata.repository.CompositeMetadataRepositoryFactory.load(CompositeMetadataRepositoryFactory.java:121)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.factoryLoad(MetadataRepositoryManager.java:60)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:767)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:668)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:107)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:102)
	at org.eclipse.equinox.internal.p2.updatechecker.UpdateChecker.getAvailableRepositories(UpdateChecker.java:149)
	at org.eclipse.equinox.internal.p2.updatechecker.UpdateChecker.checkForUpdates(UpdateChecker.java:127)
	at org.eclipse.equinox.internal.p2.updatechecker.UpdateChecker$UpdateCheckThread.run(UpdateChecker.java:75)
!SUBENTRY 1 org.eclipse.equinox.p2.metadata.repository 4 1000 2021-06-12 21:32:14.141
!MESSAGE http://dl.bintray.com/nodeclipse/nodeclipse/1.0.2f/ のリポジトリーが見つかりません。

!ENTRY org.eclipse.equinox.p2.repository 2 0 2021-06-12 21:32:45.222
!MESSAGE サーバーが lastModified <= 0 を戻しました https://raw.github.com/satyagraha/gfm_viewer/master/p2-composite/compositeContent.xml

!ENTRY org.eclipse.equinox.p2.core 4 0 2021-06-12 21:32:47.929
!MESSAGE プロビジョニング例外
!STACK 1
org.eclipse.equinox.p2.core.ProvisionException: http://dl.bintray.com/satyagraha/generic/2.0.1/ のリポジトリーが見つかりません。
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.fail(AbstractRepositoryManager.java:395)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:692)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:107)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:102)
	at org.eclipse.equinox.internal.p2.metadata.repository.CompositeMetadataRepository.addChild(CompositeMetadataRepository.java:165)
	at org.eclipse.equinox.internal.p2.metadata.repository.CompositeMetadataRepository.<init>(CompositeMetadataRepository.java:107)
	at org.eclipse.equinox.internal.p2.metadata.repository.CompositeMetadataRepositoryFactory.load(CompositeMetadataRepositoryFactory.java:121)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.factoryLoad(MetadataRepositoryManager.java:60)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:767)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:668)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:107)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:102)
	at org.eclipse.equinox.internal.p2.updatechecker.UpdateChecker.getAvailableRepositories(UpdateChecker.java:149)
	at org.eclipse.equinox.internal.p2.updatechecker.UpdateChecker.checkForUpdates(UpdateChecker.java:127)
	at org.eclipse.equinox.internal.p2.updatechecker.UpdateChecker$UpdateCheckThread.run(UpdateChecker.java:75)
!SUBENTRY 1 org.eclipse.equinox.p2.metadata.repository 4 1000 2021-06-12 21:32:47.929
!MESSAGE http://dl.bintray.com/satyagraha/generic/2.0.1/ のリポジトリーが見つかりません。

!ENTRY org.eclipse.equinox.p2.transport.ecf 4 1200 2021-06-12 21:32:50.831
!MESSAGE アーティファクトが見つかりません: https://dl.bintray.com/zaunerc/p2/com.eclipserunner.p2_site/latest/content.xml.xz.
!STACK 0
java.io.FileNotFoundException: https://dl.bintray.com/zaunerc/p2/com.eclipserunner.p2_site/latest/content.xml.xz
	at org.eclipse.equinox.internal.p2.transport.ecf.RepositoryStatusHelper.checkFileNotFound(RepositoryStatusHelper.java:297)
	at org.eclipse.equinox.internal.p2.transport.ecf.FileReader.checkException(FileReader.java:491)
	at org.eclipse.equinox.internal.p2.transport.ecf.FileReader.sendRetrieveRequest(FileReader.java:448)
	at org.eclipse.equinox.internal.p2.transport.ecf.FileReader.readInto(FileReader.java:375)
	at org.eclipse.equinox.internal.p2.transport.ecf.RepositoryTransport.download(RepositoryTransport.java:102)
	at org.eclipse.equinox.internal.p2.transport.ecf.RepositoryTransport.download(RepositoryTransport.java:158)
	at org.eclipse.equinox.internal.p2.repository.CacheManager.updateCache(CacheManager.java:402)
	at org.eclipse.equinox.internal.p2.repository.CacheManager.createCacheFromFile(CacheManager.java:132)
	at org.eclipse.equinox.internal.p2.metadata.repository.XZedSimpleMetadataRepositoryFactory.getLocalFile(XZedSimpleMetadataRepositoryFactory.java:57)
	at org.eclipse.equinox.internal.p2.metadata.repository.XZedSimpleMetadataRepositoryFactory.load(XZedSimpleMetadataRepositoryFactory.java:77)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.factoryLoad(MetadataRepositoryManager.java:60)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:767)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:668)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:107)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:102)
	at org.eclipse.equinox.internal.p2.updatechecker.UpdateChecker.getAvailableRepositories(UpdateChecker.java:149)
	at org.eclipse.equinox.internal.p2.updatechecker.UpdateChecker.checkForUpdates(UpdateChecker.java:127)
	at org.eclipse.equinox.internal.p2.updatechecker.UpdateChecker$UpdateCheckThread.run(UpdateChecker.java:75)

!ENTRY org.eclipse.equinox.p2.core 4 0 2021-06-12 21:33:46.471
!MESSAGE プロビジョニング例外
!STACK 1
org.eclipse.equinox.p2.core.ProvisionException: http://dl.bintray.com/nodeclipse/nodeclipse/1.0.2f/ のリポジトリーが見つかりません。
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.fail(AbstractRepositoryManager.java:395)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:653)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:107)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:102)
	at org.eclipse.equinox.internal.p2.metadata.repository.CompositeMetadataRepository.addChild(CompositeMetadataRepository.java:165)
	at org.eclipse.equinox.internal.p2.metadata.repository.CompositeMetadataRepository.<init>(CompositeMetadataRepository.java:107)
	at org.eclipse.equinox.internal.p2.metadata.repository.CompositeMetadataRepositoryFactory.load(CompositeMetadataRepositoryFactory.java:121)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.factoryLoad(MetadataRepositoryManager.java:60)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:767)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:668)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:107)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:102)
	at org.eclipse.equinox.internal.p2.updatechecker.UpdateChecker.getAvailableRepositories(UpdateChecker.java:149)
	at org.eclipse.equinox.internal.p2.updatechecker.UpdateChecker.checkForUpdates(UpdateChecker.java:127)
	at org.eclipse.equinox.internal.p2.updatechecker.UpdateChecker$UpdateCheckThread.run(UpdateChecker.java:75)
!SUBENTRY 1 org.eclipse.equinox.p2.metadata.repository 4 1000 2021-06-12 21:33:46.471
!MESSAGE http://dl.bintray.com/nodeclipse/nodeclipse/1.0.2f/ のリポジトリーが見つかりません。

!ENTRY org.eclipse.equinox.p2.updatechecker 4 0 2021-06-12 21:35:25.294
!MESSAGE Exception in update check thread
!STACK 0
java.lang.IllegalArgumentException: timeout value is negative
	at java.lang.Thread.sleep(Native Method)
	at org.eclipse.equinox.internal.p2.updatechecker.UpdateChecker$UpdateCheckThread.run(UpdateChecker.java:87)
!SESSION 2021-06-13 02:28:38.780 -----------------------------------------------
eclipse.buildId=4.8.0.I20180611-0500
java.version=1.8.0_172
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=ja_JP
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

!ENTRY org.eclipse.jface 2 0 2021-06-13 02:28:51.641
!MESSAGE キーバインドの競合が発生しました。 通常のアクセラレーター操作を妨げる可能性があります。
!SUBENTRY 1 org.eclipse.jface 2 0 2021-06-13 02:28:51.641
!MESSAGE ALT+CTRL+Y の競合が発生しました:
Binding(ALT+CTRL+Y,
	ParameterizedCommand(Command(org.eclipse.swtbot.generator.client.commands.import.code,SWTBot コードのインポート,
		Imports code to editor and removes it from the client recorder view,
		Category(org.eclipse.core.commands.categories.autogenerated,カテゴリーなし,自動生成コマンドかカテゴリーを持たないコマンド,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@4eba3c3f,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(ALT+CTRL+Y,
	ParameterizedCommand(Command(org.eclipse.team.svn.revision.graph.command.ShowRevisionGraphCommand,リビジョン・グラフの表示...,
		,
		Category(org.eclipse.team.svn.ui.command.category,SVN,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@7a90796c,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
!SUBENTRY 1 org.eclipse.jface 2 0 2021-06-13 02:28:51.641
!MESSAGE CTRL+SHIFT+T の競合が発生しました:
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.navigate.open.type,型を開く,
		型を Java エディターで開きます,
		Category(org.eclipse.ui.category.navigate,ナビゲート,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@6c98079,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.lsp4e.symbolinworkspace,Go to Symbol in Workspace,
		,
		Category(org.eclipse.lsp4e.category,言語サーバー,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@5135b8a3,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)

!ENTRY org.eclipse.jface 2 0 2021-06-13 02:28:57.976
!MESSAGE キーバインドの競合が発生しました。 通常のアクセラレーター操作を妨げる可能性があります。
!SUBENTRY 1 org.eclipse.jface 2 0 2021-06-13 02:28:57.976
!MESSAGE ALT+CTRL+C の競合が発生しました:
Binding(ALT+CTRL+C,
	ParameterizedCommand(Command(AnyEdit.capitalize.command,先頭文字のみ大文字,
		,
		Category(AnyEdit.category,AnyEdit ツール,AnyEdit ツール・キー・バインド,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@72337303,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.textEditorScope,,,system)
Binding(ALT+CTRL+C,
	ParameterizedCommand(Command(org.eclipse.linuxtools.changelog.core.actions.KeyActionCommand,ChangeLog エントリーの挿入,
		Insert a ChangeLog entry,
		Category(org.eclipse.linuxtools.changelog,Changelog,Changelog key bindings,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@3bc22ada,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.textEditorScope,,,system)
Binding(ALT+CTRL+C,
	ParameterizedCommand(Command(org.eclipse.team.svn.ui.command.CommitCommand,コミット...,
		,
		Category(org.eclipse.team.svn.ui.command.category,SVN,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@7c47ae7d,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)

!ENTRY org.eclipse.launchbar.core 2 0 2021-06-13 02:28:58.480
!MESSAGE Enablement expression is missing for config provider for org.eclipse.cdt.arduino.core.descriptorType

!ENTRY org.eclipse.launchbar.core 2 0 2021-06-13 02:28:58.483
!MESSAGE Enablement expression is missing for descriptor type org.eclipse.cdt.debug.core.coreBuildDescriptorType

!ENTRY org.eclipse.launchbar.core 2 0 2021-06-13 02:28:58.485
!MESSAGE Enablement expression is missing for config provider for org.eclipse.cdt.debug.core.coreBuildDescriptorType

!ENTRY org.eclipse.launchbar.core 2 0 2021-06-13 02:28:58.487
!MESSAGE Enablement expression is missing for config provider for org.eclipse.cdt.debug.core.coreBuildDescriptorType

!ENTRY org.eclipse.launchbar.core 2 0 2021-06-13 02:28:58.488
!MESSAGE Enablement expression is missing for config provider for org.eclipse.cdt.debug.core.coreBuildDescriptorType

!ENTRY org.eclipse.launchbar.core 2 0 2021-06-13 02:28:58.489
!MESSAGE Enablement expression is missing for config provider for org.eclipse.cdt.debug.core.coreBuildDescriptorType

!ENTRY org.python.pydev.shared_core 1 1 2021-06-13 02:28:58.639
!MESSAGE 存在しないファイルを追跡できません: C:\Users\tohoseal\Anaconda3\envs\python_test_project\DLLs
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Users\tohoseal\Anaconda3\envs\python_test_project\DLLs
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:54)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:459)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:440)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:66)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:88)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:156)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)

!ENTRY org.python.pydev.shared_core 1 1 2021-06-13 02:28:58.657
!MESSAGE 存在しないファイルを追跡できません: C:\Users\tohoseal\Anaconda3\envs\python_test_project\lib
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Users\tohoseal\Anaconda3\envs\python_test_project\lib
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:54)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:459)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:440)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:66)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:88)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:156)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)

!ENTRY org.python.pydev.shared_core 1 1 2021-06-13 02:28:58.658
!MESSAGE 存在しないファイルを追跡できません: C:\Users\tohoseal\Anaconda3\envs\python_test_project
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Users\tohoseal\Anaconda3\envs\python_test_project
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:54)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:459)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:440)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:66)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:88)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:156)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)

!ENTRY org.python.pydev.shared_core 1 1 2021-06-13 02:28:58.659
!MESSAGE 存在しないファイルを追跡できません: C:\Users\tohoseal\Anaconda3\envs\python_test_project\lib\site-packages
!STACK 0
java.lang.RuntimeException: Unable to track file that does not exist: C:\Users\tohoseal\Anaconda3\envs\python_test_project\lib\site-packages
	at org.python.pydev.shared_core.log.Log.logInfo(Log.java:54)
	at org.python.pydev.shared_core.path_watch.PathWatch.track(PathWatch.java:316)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:459)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.afterSetInfos(SyncSystemModulesManagerScheduler.java:440)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.registerInterpreterManager(SyncSystemModulesManagerScheduler.java:66)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler.start(SyncSystemModulesManagerScheduler.java:88)
	at org.python.pydev.plugin.PydevPlugin$1.run(PydevPlugin.java:156)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)

!ENTRY org.eclipse.epp.logging.aeri.ide 2 17 2021-06-13 02:29:04.135
!MESSAGE Server ‘org.eclipse.epp.logging.aeri.ide.server’ failed with exception: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $. ; バージョン: 2.0.7.v20170906-1327
!STACK 0
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
	at com.google.gson.Gson.fromJson(Gson.java:888)
	at com.google.gson.Gson.fromJson(Gson.java:853)
	at com.google.gson.Gson.fromJson(Gson.java:802)
	at org.eclipse.epp.internal.logging.aeri.ide.server.json.Json.deserialize(Json.java:91)
	at org.eclipse.epp.internal.logging.aeri.ide.server.mars.IO.refreshConfiguration(IO.java:66)
	at org.eclipse.epp.internal.logging.aeri.ide.server.mars.ServerConnection.startUp(ServerConnection.java:124)
	at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:62)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213)
	... 9 more

!ENTRY org.python.pydev.shared_core 4 4 2021-06-13 02:30:56.051
!MESSAGE java.io.IOException: Cannot run program "C:\Users\tohoseal\Anaconda3\envs\python_test_project\python.exe": CreateProcess error=2, 指定されたファイルが見つかりません。
!STACK 0
java.lang.RuntimeException: java.io.IOException: Cannot run program "C:\Users\tohoseal\Anaconda3\envs\python_test_project\python.exe": CreateProcess error=2, 指定されたファイルが見つかりません。
	at org.python.pydev.ast.runners.SimpleRunner.run(SimpleRunner.java:314)
	at org.python.pydev.ast.runners.SimpleRunner.run(SimpleRunner.java:280)
	at org.python.pydev.ast.runners.SimpleRunner.runAndGetOutput(SimpleRunner.java:331)
	at org.python.pydev.ast.runners.SimplePythonRunner.runAndGetOutputWithInterpreter(SimplePythonRunner.java:91)
	at org.python.pydev.ast.interpreter_managers.PythonInterpreterManager.doCreateInterpreterInfo(PythonInterpreterManager.java:67)
	at org.python.pydev.ast.interpreter_managers.PythonInterpreterManager.internalCreateInterpreterInfo(PythonInterpreterManager.java:43)
	at org.python.pydev.ast.interpreter_managers.AbstractInterpreterManager.createInterpreterInfo(AbstractInterpreterManager.java:324)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManager$CreateInterpreterInfoCallback.createInterpreterInfo(SyncSystemModulesManager.java:172)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManager.updateStructures(SyncSystemModulesManager.java:278)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler$SynchJob.run(SyncSystemModulesManagerScheduler.java:234)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
Caused by: java.io.IOException: Cannot run program "C:\Users\tohoseal\Anaconda3\envs\python_test_project\python.exe": CreateProcess error=2, 指定されたファイルが見つかりません。
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at org.python.pydev.shared_core.process.ProcessUtils.createProcess(ProcessUtils.java:105)
	at org.python.pydev.ast.runners.SimpleRunner.createProcess(SimpleRunner.java:51)
	at org.python.pydev.ast.runners.SimpleRunner.run(SimpleRunner.java:312)
	... 10 more
Caused by: java.io.IOException: CreateProcess error=2, 指定されたファイルが見つかりません。
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 14 more

!ENTRY org.python.pydev.shared_core 1 1 2021-06-13 02:30:58.832
!MESSAGE 情報: Rebuilding internal caches: C:\pleiades\workspace\atcoder\.metadata\.plugins\com.python.pydev.analysis\python_v1_7dn7h9re6mxzzbcahnwwew1sr\python.pydevsysteminfo
!STACK 0
java.lang.RuntimeException: Unable to read: C:\pleiades\workspace\atcoder\.metadata\.plugins\com.python.pydev.analysis\python_v1_7dn7h9re6mxzzbcahnwwew1sr\python.pydevsysteminfo
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalDependencyInfo.load(AbstractAdditionalDependencyInfo.java:416)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.getAdditionalSystemInfo(AdditionalSystemInterpreterInfo.java:168)
	at com.python.pydev.analysis.additionalinfo.AdditionalSystemInterpreterInfo.getAdditionalSystemInfo(AdditionalSystemInterpreterInfo.java:139)
	at com.python.pydev.analysis.system_info_builder.InterpreterInfoBuilder.syncInfoToPythonPath(InterpreterInfoBuilder.java:78)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManager.synchronizeManagerToNameToInfoPythonpath(SyncSystemModulesManager.java:392)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler$SynchJob.run(SyncSystemModulesManagerScheduler.java:257)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
Caused by: java.lang.NumberFormatException: Error getting positive int from: class LIEF::ref_iterator<class std::vector<class LIEF::ELF::Relocation 
	at org.python.pydev.shared_core.string.StringUtils.parsePositiveInt(StringUtils.java:389)
	at com.python.pydev.analysis.additionalinfo.TreeIO.loadTreeFrom(TreeIO.java:247)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalDependencyInfo.loadContentsFromFile(AbstractAdditionalDependencyInfo.java:463)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalDependencyInfo.load(AbstractAdditionalDependencyInfo.java:414)
	... 6 more

!ENTRY org.eclipse.linuxtools.docker.core 1 0 2021-06-13 02:31:02.836
!MESSAGE Failed to open connection '' on https://192.168.99.100:2376

!ENTRY org.eclipse.linuxtools.docker.core 1 0 2021-06-13 02:31:02.836
!MESSAGE Failed to open connection '' on https://192.168.99.100:2376

!ENTRY org.python.pydev.shared_core 4 4 2021-06-13 02:33:20.649
!MESSAGE ERROR reading shell. Message sent: @@IMPORTS:astropy.convolution._convolve
END@@

ProcessInfo:

 - Executed: C:\Anaconda3\python.exe -u C:\pleiades\eclipse\dropins\PyDev\eclipse\plugins\org.python.pydev.core_6.4.1.201806231219\pysrc\pycompletionserver.py 50231

 - Environment:
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\seal0\AppData\Roaming
CHOCOLATEYINSTALL=C:\ProgramData\chocolatey
CHOCOLATEYLASTPATHUPDATE=132365470270588836
COMMONPROGRAMFILES(X86)=C:\Program Files (x86)\Common Files
COMMONPROGRAMFILES=C:\Program Files\Common Files
COMMONPROGRAMW6432=C:\Program Files\Common Files
COMPOSE_CONVERT_WINDOWS_PATHS=true
COMPUTERNAME=DESKTOP-KB712J3
COMSPEC=C:\WINDOWS\system32\cmd.exe
CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2
CUDA_PATH_V10_2=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2
CUDNN_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2
DRIVERDATA=C:\Windows\System32\Drivers\DriverData
FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
FPS_BROWSER_USER_PROFILE_STRING=Default
GNUPLOT_LIB=C:\Program Files\gnuplot\demo;C:\Program Files\gnuplot\demo\games;C:\Program Files\gnuplot\share
GNUTERM=wxt
GTK_BASEPATH=C:\Program Files (x86)\GtkSharp\2.12\
HOMEDRIVE=C:
HOMEPATH=\Users\seal0
LOCALAPPDATA=C:\Users\seal0\AppData\Local
LOGONSERVER=\\DESKTOP-KB712J3
NUMBER_OF_PROCESSORS=12
NVCUDASAMPLES10_2_ROOT=C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.2
NVCUDASAMPLES_ROOT=C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.2
NVTOOLSEXT_PATH=C:\Program Files\NVIDIA Corporation\NvToolsExt\
ONEDRIVE=C:\Users\seal0\OneDrive
ONEDRIVECONSUMER=C:\Users\seal0\OneDrive
OS=Windows_NT
PATH=C:/pleiades/eclipse/jre/bin/../jre/bin/server;C:/pleiades/eclipse/jre/bin/../jre/bin;C:/pleiades/eclipse/jre/bin/../jre/lib/amd64;C:\Python38\Scripts\;C:\Python38\;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\libnvvp;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\gnuplot\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\MAMP\bin\php\php7.2.10;C:\pleiades\xampp\php;C:\ProgramData\ComposerSetup\bin;C:\Anaconda3;C:\Anaconda3\Scripts;C:\Anaconda3\Library\bin;C:\Anaconda3\Lib\site-packages;C:\Program Files\NVIDIA Corporation\Nsight Compute 2019.5.0\;C:\Program Files\CMake\bin;C:\pleiades\eclipse\mingw\bin;C:\pleiades\eclipse\msys\bin;C:\pleiades\eclipse\cygwin\bin;C:\Program Files\PuTTY\;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Users\seal0\Downloads\ffmpeg-n4.4-19-g8d172d9409-win64-gpl-4.4\bin;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin;C:\Users\seal0\AppData\Local\Microsoft\WindowsApps;C:\Users\seal0\AppData\Roaming\Composer\vendor\bin;C:\Users\seal0\AppData\Roaming\npm;C:\Program Files\JetBrains\PyCharm 2020.3.1\bin;;;C:\pleiades\eclipse;
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=9e0a
PROGRAMDATA=C:\ProgramData
PROGRAMFILES(X86)=C:\Program Files (x86)
PROGRAMFILES=C:\Program Files
PROGRAMW6432=C:\Program Files
PROMPT=$P$G
PSMODULEPATH=C:\Program Files (x86)\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\PowerShell
PUBLIC=C:\Users\Public
PYCHARM=C:\Program Files\JetBrains\PyCharm 2020.3.1\bin;
PYTHONPATH=C:\pleiades\eclipse\dropins\PyDev\eclipse\plugins\org.python.pydev.core_6.4.1.201806231219\pysrc\pydev_sitecustomize;C:\Anaconda3\DLLs;C:\Anaconda3\lib;C:\Anaconda3;C:\Anaconda3\lib\site-packages;C:\Anaconda3\lib\site-packages\win32;C:\Anaconda3\lib\site-packages\win32\lib;C:\Anaconda3\lib\site-packages\Pythonwin;C:\Anaconda3\Library\bin
SESSIONNAME=Console
SYSTEMDRIVE=C:
SYSTEMROOT=C:\WINDOWS
TEMP=C:\Users\seal0\AppData\Local\Temp
TMP=C:\Users\seal0\AppData\Local\Temp
USERDOMAIN=DESKTOP-KB712J3
USERDOMAIN_ROAMINGPROFILE=DESKTOP-KB712J3
USERNAME=seal0
USERPROFILE=C:\Users\seal0
WINDIR=C:\WINDOWS

 - Working Dir:
C:\pleiades\eclipse\dropins\PyDev\eclipse\plugins\org.python.pydev.core_6.4.1.201806231219\pysrc

 - OS:
Windows 10

 - Std output:


 - Err output:

!STACK 0
java.io.IOException: 既存の接続はリモート ホストに強制的に切断されました。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at sun.nio.ch.SocketAdaptor$SocketInputStream.read(SocketAdaptor.java:206)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
	at java.io.InputStream.read(InputStream.java:101)
	at org.python.pydev.ast.codecompletion.shell.AbstractShell.read(AbstractShell.java:455)
	at org.python.pydev.ast.codecompletion.shell.AbstractShell.read(AbstractShell.java:507)
	at org.python.pydev.ast.codecompletion.shell.AbstractShell.writeAndGetResults(AbstractShell.java:693)
	at org.python.pydev.ast.codecompletion.shell.AbstractShell.getImportCompletions(AbstractShell.java:757)
	at org.python.pydev.ast.codecompletion.revisited.modules.CompiledModule.createTokensFromServer(CompiledModule.java:376)
	at org.python.pydev.ast.codecompletion.revisited.modules.CompiledModule.<init>(CompiledModule.java:179)
	at org.python.pydev.ast.codecompletion.revisited.SystemModulesManager.getBuiltinModule(SystemModulesManager.java:322)
	at org.python.pydev.ast.codecompletion.revisited.SystemModulesManager.getModule(SystemModulesManager.java:374)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalDependencyInfo.updateKeysIfNeededAndSave(AbstractAdditionalDependencyInfo.java:259)
	at com.python.pydev.analysis.system_info_builder.InterpreterInfoBuilder.syncInfoToPythonPath(InterpreterInfoBuilder.java:160)
	at com.python.pydev.analysis.system_info_builder.InterpreterInfoBuilder.syncInfoToPythonPath(InterpreterInfoBuilder.java:86)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManager.synchronizeManagerToNameToInfoPythonpath(SyncSystemModulesManager.java:392)
	at org.python.pydev.ast.codecompletion.revisited.SyncSystemModulesManagerScheduler$SynchJob.run(SyncSystemModulesManagerScheduler.java:257)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)

!ENTRY org.eclipse.equinox.p2.core 4 0 2021-06-13 03:30:43.726
!MESSAGE プロビジョニング例外
!STACK 1
org.eclipse.equinox.p2.core.ProvisionException: http://dl.bintray.com/nodeclipse/nodeclipse/1.0.2f/ のリポジトリーが見つかりません。
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.fail(AbstractRepositoryManager.java:395)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:692)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:107)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:102)
	at org.eclipse.equinox.internal.p2.metadata.repository.CompositeMetadataRepository.addChild(CompositeMetadataRepository.java:165)
	at org.eclipse.equinox.internal.p2.metadata.repository.CompositeMetadataRepository.<init>(CompositeMetadataRepository.java:107)
	at org.eclipse.equinox.internal.p2.metadata.repository.CompositeMetadataRepositoryFactory.load(CompositeMetadataRepositoryFactory.java:121)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.factoryLoad(MetadataRepositoryManager.java:60)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:767)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:668)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:107)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:102)
	at org.eclipse.equinox.internal.p2.updatechecker.UpdateChecker.getAvailableRepositories(UpdateChecker.java:149)
	at org.eclipse.equinox.internal.p2.updatechecker.UpdateChecker.checkForUpdates(UpdateChecker.java:127)
	at org.eclipse.equinox.internal.p2.updatechecker.UpdateChecker$UpdateCheckThread.run(UpdateChecker.java:75)
!SUBENTRY 1 org.eclipse.equinox.p2.metadata.repository 4 1000 2021-06-13 03:30:43.727
!MESSAGE http://dl.bintray.com/nodeclipse/nodeclipse/1.0.2f/ のリポジトリーが見つかりません。

!ENTRY org.eclipse.equinox.p2.repository 2 0 2021-06-13 03:31:12.128
!MESSAGE サーバーが lastModified <= 0 を戻しました https://raw.github.com/satyagraha/gfm_viewer/master/p2-composite/compositeContent.xml

!ENTRY org.eclipse.equinox.p2.core 4 0 2021-06-13 03:31:14.930
!MESSAGE プロビジョニング例外
!STACK 1
org.eclipse.equinox.p2.core.ProvisionException: http://dl.bintray.com/satyagraha/generic/2.0.1/ のリポジトリーが見つかりません。
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.fail(AbstractRepositoryManager.java:395)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:692)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:107)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:102)
	at org.eclipse.equinox.internal.p2.metadata.repository.CompositeMetadataRepository.addChild(CompositeMetadataRepository.java:165)
	at org.eclipse.equinox.internal.p2.metadata.repository.CompositeMetadataRepository.<init>(CompositeMetadataRepository.java:107)
	at org.eclipse.equinox.internal.p2.metadata.repository.CompositeMetadataRepositoryFactory.load(CompositeMetadataRepositoryFactory.java:121)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.factoryLoad(MetadataRepositoryManager.java:60)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:767)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:668)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:107)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:102)
	at org.eclipse.equinox.internal.p2.updatechecker.UpdateChecker.getAvailableRepositories(UpdateChecker.java:149)
	at org.eclipse.equinox.internal.p2.updatechecker.UpdateChecker.checkForUpdates(UpdateChecker.java:127)
	at org.eclipse.equinox.internal.p2.updatechecker.UpdateChecker$UpdateCheckThread.run(UpdateChecker.java:75)
!SUBENTRY 1 org.eclipse.equinox.p2.metadata.repository 4 1000 2021-06-13 03:31:14.930
!MESSAGE http://dl.bintray.com/satyagraha/generic/2.0.1/ のリポジトリーが見つかりません。

!ENTRY org.eclipse.equinox.p2.transport.ecf 4 1200 2021-06-13 03:31:18.006
!MESSAGE アーティファクトが見つかりません: https://dl.bintray.com/zaunerc/p2/com.eclipserunner.p2_site/latest/content.xml.xz.
!STACK 0
java.io.FileNotFoundException: https://dl.bintray.com/zaunerc/p2/com.eclipserunner.p2_site/latest/content.xml.xz
	at org.eclipse.equinox.internal.p2.transport.ecf.RepositoryStatusHelper.checkFileNotFound(RepositoryStatusHelper.java:297)
	at org.eclipse.equinox.internal.p2.transport.ecf.FileReader.checkException(FileReader.java:491)
	at org.eclipse.equinox.internal.p2.transport.ecf.FileReader.sendRetrieveRequest(FileReader.java:448)
	at org.eclipse.equinox.internal.p2.transport.ecf.FileReader.readInto(FileReader.java:375)
	at org.eclipse.equinox.internal.p2.transport.ecf.RepositoryTransport.download(RepositoryTransport.java:102)
	at org.eclipse.equinox.internal.p2.transport.ecf.RepositoryTransport.download(RepositoryTransport.java:158)
	at org.eclipse.equinox.internal.p2.repository.CacheManager.updateCache(CacheManager.java:402)
	at org.eclipse.equinox.internal.p2.repository.CacheManager.createCacheFromFile(CacheManager.java:132)
	at org.eclipse.equinox.internal.p2.metadata.repository.XZedSimpleMetadataRepositoryFactory.getLocalFile(XZedSimpleMetadataRepositoryFactory.java:57)
	at org.eclipse.equinox.internal.p2.metadata.repository.XZedSimpleMetadataRepositoryFactory.load(XZedSimpleMetadataRepositoryFactory.java:77)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.factoryLoad(MetadataRepositoryManager.java:60)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:767)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:668)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:107)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:102)
	at org.eclipse.equinox.internal.p2.updatechecker.UpdateChecker.getAvailableRepositories(UpdateChecker.java:149)
	at org.eclipse.equinox.internal.p2.updatechecker.UpdateChecker.checkForUpdates(UpdateChecker.java:127)
	at org.eclipse.equinox.internal.p2.updatechecker.UpdateChecker$UpdateCheckThread.run(UpdateChecker.java:75)

!ENTRY org.eclipse.equinox.p2.core 4 0 2021-06-13 03:32:12.084
!MESSAGE プロビジョニング例外
!STACK 1
org.eclipse.equinox.p2.core.ProvisionException: http://dl.bintray.com/nodeclipse/nodeclipse/1.0.2f/ のリポジトリーが見つかりません。
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.fail(AbstractRepositoryManager.java:395)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:653)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:107)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:102)
	at org.eclipse.equinox.internal.p2.metadata.repository.CompositeMetadataRepository.addChild(CompositeMetadataRepository.java:165)
	at org.eclipse.equinox.internal.p2.metadata.repository.CompositeMetadataRepository.<init>(CompositeMetadataRepository.java:107)
	at org.eclipse.equinox.internal.p2.metadata.repository.CompositeMetadataRepositoryFactory.load(CompositeMetadataRepositoryFactory.java:121)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.factoryLoad(MetadataRepositoryManager.java:60)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:767)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:668)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:107)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:102)
	at org.eclipse.equinox.internal.p2.updatechecker.UpdateChecker.getAvailableRepositories(UpdateChecker.java:149)
	at org.eclipse.equinox.internal.p2.updatechecker.UpdateChecker.checkForUpdates(UpdateChecker.java:127)
	at org.eclipse.equinox.internal.p2.updatechecker.UpdateChecker$UpdateCheckThread.run(UpdateChecker.java:75)
!SUBENTRY 1 org.eclipse.equinox.p2.metadata.repository 4 1000 2021-06-13 03:32:12.084
!MESSAGE http://dl.bintray.com/nodeclipse/nodeclipse/1.0.2f/ のリポジトリーが見つかりません。

!ENTRY org.eclipse.equinox.p2.updatechecker 4 0 2021-06-13 03:33:44.473
!MESSAGE Exception in update check thread
!STACK 0
java.lang.IllegalArgumentException: timeout value is negative
	at java.lang.Thread.sleep(Native Method)
	at org.eclipse.equinox.internal.p2.updatechecker.UpdateChecker$UpdateCheckThread.run(UpdateChecker.java:87)

!ENTRY org.eclipse.ui 4 0 2021-06-13 04:30:28.970
!MESSAGE 未処理のイベント・ループ例外
!STACK 0
org.eclipse.e4.core.di.InjectionException: java.lang.NullPointerException
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:65)
	at org.eclipse.e4.ui.internal.di.UIEventObjectSupplier$UIEventHandler$1.run(UIEventObjectSupplier.java:64)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:233)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:144)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4567)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application$1.syncExec(E4Application.java:212)
	at org.eclipse.e4.ui.internal.di.UIEventObjectSupplier$UIEventHandler.handleEvent(UIEventObjectSupplier.java:61)
	at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:201)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:196)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:135)
	at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:78)
	at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:39)
	at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:52)
	at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:60)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:374)
	at org.eclipse.e4.ui.model.application.ui.impl.UIElementImpl.setVisible(UIElementImpl.java:346)
	at org.eclipse.e4.ui.workbench.renderers.swt.ContributionRecord.updateVisibility(ContributionRecord.java:110)
	at org.eclipse.e4.ui.workbench.renderers.swt.MenuManagerRendererFilter.updateElementVisibility(MenuManagerRendererFilter.java:191)
	at org.eclipse.e4.ui.workbench.renderers.swt.MenuManagerRendererFilter.updateElementVisibility(MenuManagerRendererFilter.java:202)
	at org.eclipse.e4.ui.workbench.renderers.swt.MenuManagerShowProcessor.showMenu(MenuManagerShowProcessor.java:255)
	at org.eclipse.e4.ui.workbench.renderers.swt.MenuManagerShowProcessor.menuAboutToHide(MenuManagerShowProcessor.java:112)
	at org.eclipse.jface.internal.MenuManagerEventHelper.showEventPostHelper(MenuManagerEventHelper.java:92)
	at org.eclipse.jface.action.MenuManager.handleAboutToShow(MenuManager.java:471)
	at org.eclipse.jface.action.MenuManager.access$1(MenuManager.java:465)
	at org.eclipse.jface.action.MenuManager$2.menuShown(MenuManager.java:497)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:256)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4118)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1052)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1076)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
	at org.eclipse.swt.widgets.Control.WM_INITMENUPOPUP(Control.java:5125)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4794)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:345)
	at org.eclipse.swt.widgets.Decorations.windowProc(Decorations.java:1499)
	at org.eclipse.swt.widgets.Shell.windowProc(Shell.java:2159)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4757)
	at org.eclipse.swt.internal.win32.OS.TrackPopupMenu(Native Method)
	at org.eclipse.swt.widgets.Menu._setVisible(Menu.java:250)
	at org.eclipse.swt.widgets.Display.runPopups(Display.java:3972)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3528)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1170)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1059)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:667)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:597)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:656)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:592)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1498)
Caused by: java.lang.NullPointerException
	at org.eclipse.tm4e.ui.internal.menus.ThemeContribution.getContributionItems(ThemeContribution.java:58)
	at org.eclipse.ui.actions.CompoundContributionItem.getContributionItemsToFill(CompoundContributionItem.java:80)
	at org.eclipse.ui.actions.CompoundContributionItem.fill(CompoundContributionItem.java:54)
	at org.eclipse.ui.internal.menus.DynamicMenuContributionItem.fill(DynamicMenuContributionItem.java:147)
	at org.eclipse.jface.action.MenuManager.doItemFill(MenuManager.java:728)
	at org.eclipse.jface.action.MenuManager.update(MenuManager.java:810)
	at org.eclipse.jface.action.MenuManager.update(MenuManager.java:669)
	at org.eclipse.e4.ui.workbench.renderers.swt.MenuManagerRenderer.scheduleManagerUpdate(MenuManagerRenderer.java:1219)
	at org.eclipse.e4.ui.workbench.renderers.swt.MenuManagerRenderer.subscribeUIElementTopicAllRenderedVisibility(MenuManagerRenderer.java:200)
	at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	... 64 more
